name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean compile

  test:
    name: Test
    runs-on: windows-latest
    needs: build  # Exécute le job Test après Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        #run: mvn clean test -Dtest=**/Intergration/**/*
        run: mvn clean test
"""
  quality:
    name: Quality Check (SonarQube)
    runs-on: windows-latest
    needs: test  # Exécute la qualité après Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=ton-projet -Dsonar.organization=ton-org -Dsonar.host.url=https://sonarcloud.io
"""