name: Java Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies and run unit tests
        run: mvn clean test -Dtest=**/Intergration/**/*
        #run: mvn clean test
